# Generated by Django 4.2.7 on 2025-01-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/default.png', upload_to='profile_pics/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
