# Generated by Django 4.2.7 on 2025-01-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_picture_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.png', upload_to='profile_pics/'),
        ),
    ]
