# Generated by Django 4.2.7 on 2025-01-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_allergies_user_blood_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medical_conditions',
        ),
    ]
